// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"database/sql"
	"github.com/go-playground/validator/v10"
	"github.com/mailjet/mailjet-apiv3-go/v4"
)

// Injectors from wire.go:

func Wire(validate *validator.Validate, db *sql.DB, mail *mailjet.Client) *Router {
	repository := ProvideRepository()
	service := ProvideService(repository, db, mail)
	handler := ProvideHandler(validate, service)
	router := ProvideRouter(handler)
	return router
}
